services:

  api-gateway:
    build: ./
    container_name: api-gateway
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./api-gateway:/api-gateway
    networks:
      - dev

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nummus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

networks:

  dev:
    driver: bridge

volumes:

  postgres_data:
